### ISSUE TITLE
Exception for ProfiMail notification

### ISSUE THREAD

**Issue by a20god** [graynada/GeminiLED#1]
My attempt to make GeminiLED support ProfiMail failed due to this problem:
When ProfiMail Go (https://play.google.com/store/apps/details?id=com.lonelycatgames.PM) receives a mail, GeminiLED will throw an exception:

> 6-30 20:17:04.553 9928-9928/harby.graham.geminiled I/GeminiLED: Notification from: com.lonelycatgames.PM title: null
> 06-30 20:17:04.700 9928-9928/harby.graham.geminiled W/Bundle: Key android.title expected String but value was a android.text.SpannableString.  The default value <null> was returned.
> 06-30 20:17:04.700 9928-9928/harby.graham.geminiled W/Bundle: Attempt to cast generated internal exception:
>     java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
>         at android.os.BaseBundle.getString(BaseBundle.java:995)
>         at harby.graham.geminiled.GeminiNotificationListener.onNotificationPosted(GeminiNotificationListener.java:42)

**Comment by a20god** [comment]
Using

>        String title = sbn.getNotification().extras.getCharSequence("android.title").toString();

in onNotificationPosted() and onNotificationRemoved() seems to work for me.

**Comment by Eeems** [comment]
https://stackoverflow.com/a/27479231
You'd want to update [app/src/main/java/harby/graham/geminiled/GeminiNotificationListener.java#L42](https://github.com/graynada/GeminiLED/blob/master/app/src/main/java/harby/graham/geminiled/GeminiNotificationListener.java#L42) to handle either a String or a SpannableString.

**Comment by a20god** [comment]
BTW, as ProfilMail keeps showing a notification while it is online, therefore looking at the package name won't be enough (unless GeminiLED turns on the LED iff there are two or more notiifications from "com.lonelycatgames.PM").

**Comment by a20god** [comment]
@Eems: I think that won't work. Look again at the log and note that both getString() fails for "android.title" if the value is a SpannableString. get() also fails. That's why I suggested using getCharSequence().

**Comment by graynada** [comment]
Thanks for the feedback.
I'll incorporate 
```
String title = sbn.getNotification().extras.getCharSequence("android.title").toString();
```
Thinking about the multiple notifications from a single package.  I can add a feature to only light the LED on a given packages notification if it contains a title, ie its from someone.  Would this work with what you have seen from the notification log ofProfilMail?

**Comment by Eeems** [comment]
@a20god It's Eeems not Eems fyi

**Comment by a20god** [comment]
Well, for ProfiMail, the title of the notification used by ProfiMail to indicate online/offline status is (IIRC) "ProfiMail Go", the title of the other notifications is (part of?) the subject header line. There might be other values in the extras bundle which could be used to distinguish a mail having subject "ProfiMail Go" from the online/offline annotation. For instance, the "got mail" notifications have "Reply" and "Next" buttons.

**Comment by a20god** [comment]
I had another look:

ProfiMail going online:
android.title=ProfiMail Go
android.text=Connected

ProfiMail going offline:
android.title=ProfiMail Go
android.text=

ProfiMail receiving mail:
android.title=   SUBJECT
android.text=SENDER

(I don't know where those spaces preceding SUBJECT come from, perhaps some markup as there's a bar preceding the subject in the notification, the color of which probably indicating the mail account.)

Maybe counting the notifications is a simpler approach than trying to make the above user-configurable.

**Comment by graynada** [comment]
@a20god The trouble is there seems to be no standard in compiling notifications. All the applications I have been using it with put the contact name as the title where as PM is from your description putting it in the text.  With K9 you can select in settings to stop notifications for checking/sending mail and in this way it only triggers on mail received.  Is this possible in PM to stop triggers for non message notifications?

At the moment I'd quiet like to focus on getting the user configuration aspects sorted over trying to solve this currently single use case, and come back to this later especially if there are more applications that need a work around.  That way I would hopefully be able to come up with a single solution to them all.

**Comment by a20god** [comment]
I don't think PM can be configured to not display that notification. Using the number of notifications for deciding whether to turn the LED on or off might also help for other apps.

**Comment by a20god** [comment]
Here's my patch for making GeminiLED work with ProfiMail (using the number of notifications):

[PM-patch.txt](https://github.com/graynada/GeminiLED/files/2152210/PM-patch.txt)

**Comment by a20god** [comment]
Apparently, the "android.title" value can be null:

> 07-01 00:43:58.631 5051-5051/harby.graham.geminiled E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: harby.graham.geminiled, PID: 5051
>     java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
>         at harby.graham.geminiled.GeminiNotificationListener.onNotificationPosted(GeminiNotificationListener.java:42)

I suggest doing this in onNotificationPosted() (and similarly in onNotificationRemove()):

        CharSequence title = sbn.getNotification().extras.getCharSequence("android.title");
        String text = "Notification from: " + pack;
        if (title != null) {
            text = text + ", title: " + title.toString();
        }

**Comment by graynada** [comment]
Thanks for all the inputs.  I have added to following method to get title and text from notifications

      String` getTitleAndText(StatusBarNotification sbn){
        Bundle extras = sbn.getNotification().extras;
        CharSequence title = "";
        CharSequence text = "";
        if (extras != null) {
            title = extras.getCharSequence("android.title");
            text = extras.getCharSequence("android.text");
        }
        return " Title: " + title + " Text: " + text;
    }

And called that from the notification posted and removed methods.  This should overcome previous null pointer exceptions and any that may have arisen from CharSequence.toString() calls.
Ultimately I do not need the title or the text at this stage, I left that in for contact identification later but that will require the ability to flash LEDs.  

As I mentioned before I will have a look at the ProfilMail unique (so far) use case once I have the user customisation sorted out.  Using contacts maybe the answer, or setting a filter text for the notification title/text.  I have had a quick look at @a20god yor solution you kindly provide but as well as have the potential .toString() trap I've avoided above it would appear to be looking to invoke LED 6 which I think is the power one, if not its the Wifi/Bluetooth one neither of which I was not going to use with this app.

**Comment by a20god** [comment]
Oops, I misunderstood your code, therefore my patch counts notifications per LED rather than notifications per package name. (And in the code I'm actually using on my Gemini I just modified the K9 configuration, therefore the LED index is correct). Sorry. Looking forward to the next version...

**Comment by a20god** [comment]
I think your new getTitleAndText() still fails if extras.getCharSequence() returns null.
What do you think about this?

    private String addExtrasString(String soFar, StatusBarNotification sbn, String key, String title)
    {
        if (sbn.getNotification().extras == null) {
            return soFar;
        }
        CharSequence cs = sbn.getNotification().extras.getCharSequence(key);
        if (cs == null) {
            return soFar;
        }
        return soFar + ", " + title + ": " + cs.toString ();
    }

    @Override
    public void onNotificationPosted(StatusBarNotification sbn) {

        String pack = sbn.getPackageName();
        String text = "Notification from: " + pack;
        text = addExtrasString(text, sbn, "android.title", "title")
        text = addExtrasString(text, sbn, "android.text", "text")
        Log.i(GeminiLED.TAG, text);

        loadActiveLEDList();
    }

**Comment by graynada** [comment]
@a20god Have you had any actual failures?  I've been monitoring off and on all day and had no issues despite numerous notifications with either null title or text.  It seems a getCarSequence() return of null just concatenates to 'null' which is just fine for me.

**Comment by a20god** [comment]
Yes, see comment 13. It was somehow related to Android and/or PM going online or offline:

> java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference

**Comment by graynada** [comment]
@a20god If I'm counting correctly that was before I updated the code . Have you had any failures with the apk I posted this morning as it doesn't contain toString() any more I think? I have had a few notifications with null titles and they have been handled fine with this version.

**Comment by a20god** [comment]
So far, I had no failures with the new code. It uses implicit String.valueOf() calls which do not fail for null values.

**Comment by graynada** [comment]
@a20god OK thanks for the confirmation so I think this issue is now closed.
