### ISSUE TITLE
GeminiLED should start on boot.

### ISSUE THREAD

**Issue by a20god** [graynada/GeminiLED#2]
GeminiLED should start on boot.

**Comment by graynada** [comment]
Agreed although the Service does restart on boot if running at previous shutdown which provides continued functionality of notifications on the LEDs

**Comment by graynada** [comment]
Having done some research Android automatically restarts previously running Services on boot and it is recommended to let the system handle this.  I have tested this and this is true for the GeminiLED Service that provides the LED lighting on notification.  The user would not want the Activity started on boot so GeminiLED currently behaves as would be wanted on boot already.
