### ISSUE TITLE
Cannot remove app from LED

### ISSUE THREAD

**Issue by a20god** [graynada/GeminiLED#4]
I haven't found any way to revert the configuration of a LED to no app at all (short of uninstalling and reinstalling GeminiLED, presumably). The best I found is assigning an app which never shows a notification.

**Comment by graynada** [comment]
That is the only way at the moment, I will add a long click feature to enable that and set the GeminiLED icon

**Comment by graynada** [comment]
This feature request will be captured in the next release. Not an issue or bug as such so closing.
