### ISSUE TITLE
LED is flashing without notification

### ISSUE THREAD

**Issue by a20god** [graynada/GeminiLED#5]
I configured one LED and that LED gets switched on for a brief moment about once in a couple of minutes while the Gemini is closed even if there is no notification. Could be a firmware bug.

**Comment by graynada** [comment]
For which app is it please? Some apps like email activate notifications momentarily when checking mailing etc.

**Comment by a20god** [comment]
ProfiMail Go, with "Show status of background work" disabled so that it displays a notification only if a message has been received. Perhaps ProfiMail very briefly displays a notification if it cannot connect to the server (my Gemini was closed and offline). As logging is disabled in the released version of GeminiLED, logcat remained silent. I'll try to build GeminiLED with logging enabled and try again.

**Comment by graynada** [comment]
I suspect that will be the case although some apps do funny things with notifications.  Handcent Next SMS for example. If I clear the notification without reading the message it will clear the current notification flag but reinstate it silently a few minutes later.  This is behaviour I have observed with my GeminiLED app and with the notification LED on my previous 2 phones.  Unfortunately not all apps play fair in this game and it is impossible to configure GeminiLED to the behaviour of individual apps.

I am however looking to add advanced options to each LED and this will include white or black listing.  Here it would be possible to allow ignoring of 'empty' notifications.  I will enable the user to select to log notifications in the advanced settings so they can learn what triggers what.

I propose to close this issue as it is not an issue with GeminiLED it is a feature of how ProfMail uses the notification service.

**Comment by a20god** [comment]
I rebooted (due to playing with Linux) and installed a version of GeminiLED with logging enabled. Now, the issue is gone, the LED no longer flashes.

**Comment by graynada** [comment]
OK sounds like Prof Mail doing something so not an issue with GeminiLED so closing this.
